# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish Node.js Package to NPM

on:
  push:
    branches:
      - main

jobs:
  cdn-publish:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v3'
        with:
          ref: ${{ github.ref }}
          persist-credentials: false
      - name: Reconfigure git to use HTTP authentication and install dependencies
        run: |
          git config --global url.https://${{ secrets.ICONS_TOKEN }}@github.com/.insteadOf ssh://git@github.com/
          npm ci
      - run: npm run build:widget
      - name: 'Commit and publish to cdn'
        uses: EndBug/add-and-commit@v4
        with:
          author_name: NethBot
          author_email: NethBot@users.noreply.github.com
          message: 'widget: release for jsDelivr'
          add: 'dist-widget/ --force'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  npm-publish:
    needs: cdn-publish
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v3'
        with:
          ref: ${{ github.ref }}
          persist-credentials: false
      - name:  'Version Bump'
        uses:  'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: NethBot
          GITHUB_EMAIL: NethBot@users.noreply.github.com
        with:
          version-type:  'patch'
          commit-message: 'package.json: version bump to {{version}}'
      - name: 'Publish to npm repository'
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Reconfigure git to use HTTP authentication and install dependencies
        run: |
          git config --global url.https://${{ secrets.ICONS_TOKEN }}@github.com/.insteadOf ssh://git@github.com/
          npm ci
      - run: npm run build
      - run: npm run release
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
